package dev.isxander.mixinconflicthelper.gui;

import dev.isxander.mixinconflicthelper.utils.Mod;
import net.fabricmc.loader.api.ModContainer;
import net.fabricmc.loader.impl.FabricLoaderImpl;
import net.fabricmc.loader.impl.util.LoaderUtil;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class SwingPopups {
    public static void showConflict(ModContainer mod1Container, ModContainer mod2Container, Throwable th) throws IOException {
        var mod1 = Mod.fromModContainer(mod1Container);
        var mod2 = Mod.fromModContainer(mod2Container);

        var sw = new StringWriter();
        var pw = new PrintWriter(sw);
        th.printStackTrace(pw);
        var stacktrace = sw.toString();

        var provider = FabricLoaderImpl.INSTANCE.tryGetGameProvider();
        if (provider == null && LoaderUtil.hasAwtSupport()
                || provider != null && provider.hasAwtSupport()) {
            System.setProperty("java.awt.headless", "false");

            conflict(mod1, mod2, stacktrace);

            System.setProperty("java.awt.headless", "true");
        } else {
            // most likely MacOS
            System.out.println("Forking process to display swing GUI!");
            var javaBinPath = LoaderUtil.normalizePath(Paths.get(System.getProperty("java.home"), "bin"));
            var executables = new String[]{ "javaw.exe", "java.exe", "java" };
            Path javaPath = null;
            for (String executable : executables) {
                Path path = javaBinPath.resolve(executable);

                if (Files.isRegularFile(path)) {
                    javaPath = path;
                    break;
                }
            }

            if (javaPath == null) throw new RuntimeException("Couldn't find java executable in " + javaBinPath);

            var process = new ProcessBuilder(javaPath.toString(), "-cp", System.getProperty("java.class.path"), SwingPopups.class.getName())
                    .redirectOutput(ProcessBuilder.Redirect.INHERIT)
                    .redirectError(ProcessBuilder.Redirect.INHERIT)
                    .start();

            try (var os = new DataOutputStream(process.getOutputStream())) {
                mod1.writeTo(os);
                mod2.writeTo(os);
                os.writeUTF(stacktrace);
            }
        }
    }

    public static void conflict(Mod mod1, Mod mod2, String stacktrace) {
        var message = createPopupMessage(mod1, mod2);

        var option = JOptionPane.showOptionDialog(
                null,
                message, "Mixin Conflict Helper",
                JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE,
                null,
                new String[]{ mod1.name(), mod2.name(), "Copy issue template" },
                0
        );

        switch (option) {
            case 0 -> openUrl(mod1.issuesUrl().orElseThrow());
            case 1 -> openUrl(mod2.issuesUrl().orElseThrow());

            case 2 -> {
                var clipboardContent = """
                   *Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
                    
                   [%s](%s) is conflicting with [%s](%s).
                   
                   ```
                   %s
                   ```
                    """.stripIndent().formatted(mod1.name(), mod1.sourcesUrl().orElse("#"), mod2.name(), mod2.sourcesUrl().orElse("#"), stacktrace);

                Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(clipboardContent), null);

                conflict(mod1, mod2, stacktrace);
            }
        }
    }

    private static String createPopupMessage(Mod mod1, Mod mod2) {
        var mod1Conflicts = mod1.conflicts().stream().anyMatch((dep) -> dep.equals(mod2.id()));
        var mod2Conflicts = mod2.conflicts().stream().anyMatch((dep) -> dep.equals(mod1.id()));

        var sb = new StringBuilder();
        sb.append("There has been a mod conflict due to Mixin.").append("\n\n");
        sb.append(mod1.name()).append(" conflicted with ").append(mod2.name()).append(". ").append("\n");
        if (mod1Conflicts || mod2Conflicts) {
            sb.append("The creator of ").append(mod1Conflicts ? mod1.name() : mod2.name()).append(" knows about the issue, so they advise you to use either mod.");
        } else {
            sb.append("To continue running the game, you should remove one of the mods.");
        }
        sb.append("\n\n");

        sb.append("Pressing the buttons below takes you to their respected issue page.");

        return sb.toString();
    }

    public static void main(String[] args) throws Exception {
        System.setProperty("apple.awt.application.appearance", "system");
        System.setProperty("apple.awt.application.name", "Mixin Conflict Helper");

        var is = new DataInputStream(System.in);
        var mod1 = Mod.fromDataInputStream(is);
        var mod2 = Mod.fromDataInputStream(is);
        var stacktrace = is.readUTF();

        SwingUtilities.invokeAndWait(() -> conflict(mod1, mod2, stacktrace));

        System.exit(0);
    }

    private static void openUrl(String url) {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (URISyntaxException | IOException e) {
            e.printStackTrace();
        }
    }
}
